# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         result
version:      1.101
version_from: result.pm
installdirs:  site
requires:
    Data::Dump:                    0
    strict:                        0
    Test::Easy:                    0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
